# Generated by Django 3.1.7 on 2021-03-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_console'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Console',
        ),
    ]
